version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    restart: on-failure:10
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mypassword
    ports:
      - '3307:3306'
    volumes:
      - ./dbdata:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/ssl/